export const UPDATE_TOKEN = 'UPDATE_TOKEN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';

export const REQUEST_POLLS = 'REQUEST_POLLS';
export const RECIEVED_POLLS = 'RECIEVED_POLLS';
export const ERROR_POLLS = 'ERROR_POLLS';

export const REQUEST_UPDATE_CLICK = 'REQUEST_UPDATE_CLICK';
export const RECIEVED_UPDATE_CLICK = 'RECIEVED_UPDATE_CLICK';
export const ERROR_UPDATE_CLICK = 'ERROR_UPDATE_CLICK';
export const RECIEVED_RESET_CLICK = 'RECIEVED_RESET_CLICK';
